export const defaultBusinessProfile = {
  // This is the public salon card the site reads for contact and branding.
  // It is the first thing the homepage, footer, and contact page all pull from.
  name: "Sibs Style Beauty Lounge",
  // The tagline is the short marketing line that sits under the brand name.
  tagline: "Bespoke beauty services tailored for you",
  // The longer description gives the site a calmer, editorial tone.
  description:
    "An editorial skincare destination where each visit is curated through texture, scent, and scientific precision.",
  // These contact details show up everywhere a visitor might try to reach the lounge.
  email: "mcjalandoni@yahoo.com",
  phone: "052 906 3016",
  // The address is split into parts so the UI can display it in different layouts.
  addressLine1: "Al Hashar Building - Salah Al Din St - Office no 301 - Main Road",
  addressLine2: "next to Crown Plaza Hotel - Muteena - Deira",
  city: "Dubai",
  state: "",
  postalCode: "UAE",
  // Availability logic needs the local timezone so days and opening hours stay correct.
  timezone: "Asia/Dubai",
  // The logo is used as a brand image in the header and any future marketing cards.
  logoUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop",
  // This link lets the site open directions directly in Google Maps.
  googleMapsUrl: "https://share.google/lWLJiTBONnJlR29z7",
  // Social links are surfaced in the footer and mobile navigation.
  socialInstagram: "https://www.instagram.com/sibsstylebeauty?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
  socialFacebook: "https://www.facebook.com/profile.php?id=61584300861932",
  // These are the human-readable opening-hour labels shown on the contact page.
  openingHours: {
    mondayFriday: "Monday OFF | Tuesday-Thursday 10:00 AM - 9:00 PM | Friday-Sunday 10:00 AM - 10:00 PM",
    saturday: "Saturday 10:00 AM - 10:00 PM",
    sunday: "Sunday 10:00 AM - 10:00 PM",
  },
  // The booking page uses this same address when it creates a new appointment.
  // The weekly schedule is the machine-readable version that powers availability checks.
  weeklyHours: {
    monday: "OFF",
    tuesday: "10:00 AM - 9:00 PM",
    wednesday: "10:00 AM - 9:00 PM",
    thursday: "10:00 AM - 9:00 PM",
    friday: "10:00 AM - 10:00 PM",
    saturday: "10:00 AM - 10:00 PM",
    sunday: "10:00 AM - 10:00 PM",
  },
  // The booking page loops over these labels when it builds the calendar slots.
  standardSlots: [
    "10:00 AM",
    "11:00 AM",
    "12:00 PM",
    "01:00 PM",
    "02:00 PM",
    "03:00 PM",
    "04:00 PM",
    "05:00 PM",
    "06:00 PM",
    "07:00 PM",
    "08:00 PM",
    "09:00 PM",
  ],
  // Lead time keeps same-day bookings from being too last minute.
  bookingLeadMinutes: 0,
  // The app uses one-hour steps when it compares services and openings.
  bookingIntervalMinutes: 60,
  // If Convex has no profile yet, these defaults keep the app usable on first launch.
};

// The single appointment location is reused everywhere so the booking data stays consistent.
export const defaultAppointmentLocation =
  "Al Hashar Building - Salah Al Din St - Office no 301 - Main Road - next to Crown Plaza Hotel - Muteena - Deira, Dubai, UAE";

// Each service follows the same shape so the UI can render cards, details, and booking info from one list.
export const defaultServices = [
  // Hair Services
  {
    slug: "hair-wash-dry",
    name: "Hair Wash & Dry",
    shortDescription: "A clean, polished blow-dry finish for a fresh everyday look.",
    fullDescription: "A smooth salon wash and dry service designed to leave the hair refreshed, lightweight, and ready to style.",
    priceCents: 5000,
    priceLabel: "AED 50",
    durationMinutes: 45,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 1,
    keyBenefits: ["Fresh finish", "Polished style", "Salon care"],
  },
  {
    slug: "blow-dry-iron",
    name: "Blow Dry & Iron",
    shortDescription: "Sleek heat-styled finish with a smooth, glossy result.",
    fullDescription: "A styled blow-dry paired with iron work for a refined, smooth finish that lasts beyond the appointment.",
    priceCents: 8000,
    priceLabel: "AED 80 (minimum)",
    durationMinutes: 60,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1522337654092-2b5742b5a5f7?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 2,
    keyBenefits: ["Smooth finish", "Heat styling", "Glossy result"],
  },
  {
    slug: "wave-retro",
    name: "Wave / Retro",
    shortDescription: "Soft retro waves for volume and movement.",
    fullDescription: "A classic waved styling service that creates polished movement and a soft, elegant silhouette.",
    priceCents: 5000,
    priceLabel: "AED 50 (minimum)",
    durationMinutes: 45,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 3,
    keyBenefits: ["Retro shape", "Soft movement", "Event styling"],
  },
  {
    slug: "hair-color",
    name: "Hair Color",
    shortDescription: "Full-color transformation with salon guidance.",
    fullDescription: "A complete color service for changing tone, refreshing faded color, or creating a new seasonal look.",
    priceCents: 15000,
    priceLabel: "AED 150 (minimum)",
    durationMinutes: 120,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 4,
    keyBenefits: ["Color refresh", "Custom tone", "Glossy finish"],
  },
  {
    slug: "roots-color",
    name: "Roots Color",
    shortDescription: "Root touch-up for seamless color maintenance.",
    fullDescription: "A maintenance color service that softens regrowth and keeps the color story looking even and intentional.",
    priceCents: 10000,
    priceLabel: "AED 100 (minimum)",
    durationMinutes: 90,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1595872018818-97555653a011?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 5,
    keyBenefits: ["Root blend", "Color maintenance", "Seamless finish"],
  },
  {
    slug: "highlights",
    name: "Highlights",
    shortDescription: "Bright dimensional lightening through the hair.",
    fullDescription: "A highlight service designed to add brightness, depth, and dimension while keeping the overall look balanced.",
    priceCents: 20000,
    priceLabel: "AED 200 (minimum)",
    durationMinutes: 150,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1527537367824-cc4c7eb5d3f7?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 6,
    keyBenefits: ["Brightness", "Dimension", "Salon precision"],
  },
  {
    slug: "balayage",
    name: "Balayage",
    shortDescription: "Hand-painted lightening with soft lived-in blending.",
    fullDescription: "A hand-painted color technique that creates a natural gradation of light and depth with a seamless grow-out.",
    priceCents: 20000,
    priceLabel: "AED 200 (minimum)",
    durationMinutes: 160,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1560869713-7dcae6a4fdc6?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 7,
    keyBenefits: ["Hand-painted", "Soft blend", "Low maintenance"],
  },
  {
    slug: "keratin-treatment",
    name: "Keratin Treatment",
    shortDescription: "Smoothing service for softer, sleeker strands.",
    fullDescription: "A restorative smoothing treatment that helps reduce frizz, soften texture, and make styling easier between visits.",
    priceCents: 18000,
    priceLabel: "AED 180 (minimum)",
    durationMinutes: 140,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 8,
    keyBenefits: ["Frizz control", "Soft texture", "Sleek styling"],
  },
  {
    slug: "protein-treatment",
    name: "Protein Treatment",
    shortDescription: "Strengthening care for hair that needs repair.",
    fullDescription: "A protein-rich strengthening ritual that supports elasticity, resilience, and a healthier overall feel.",
    priceCents: 18000,
    priceLabel: "AED 180 (minimum)",
    durationMinutes: 120,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 9,
    keyBenefits: ["Strength support", "Repair care", "Healthier feel"],
  },
  {
    slug: "rebonding",
    name: "Rebonding",
    shortDescription: "Longer-lasting straightening and smoothing service.",
    fullDescription: "A more intensive straightening ritual designed for clients who want a smooth, sleek, and polished finish.",
    priceCents: 18000,
    priceLabel: "AED 180 (minimum)",
    durationMinutes: 180,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 10,
    keyBenefits: ["Straightening", "Smooth finish", "Long wear"],
  },
  {
    slug: "haircut",
    name: "Haircut",
    shortDescription: "Precision cutting for shape and polish.",
    fullDescription: "A tailored haircut that refreshes shape, weight, and movement with a clean salon finish.",
    priceCents: 4000,
    priceLabel: "AED 40",
    durationMinutes: 45,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 11,
    keyBenefits: ["Precision shape", "Fresh style", "Clean finish"],
  },
  {
    slug: "hair-spa",
    name: "Hair Spa",
    shortDescription: "Nourishing scalp and hair therapy.",
    fullDescription: "A relaxing hair spa ritual focused on hydration, scalp comfort, and overall hair vitality.",
    priceCents: 6000,
    priceLabel: "AED 60",
    durationMinutes: 60,
    category: "Hair Services",
    imageUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 12,
    keyBenefits: ["Hydration", "Scalp comfort", "Hair vitality"],
  },

  // Nail Care
  {
    slug: "mani-pedi-foot-spa",
    name: "Mani / Pedi with Foot Spa",
    shortDescription: "Classic hand and foot care with a spa finish.",
    fullDescription: "A polished manicure and pedicure experience paired with a soothing foot spa for a full refresh.",
    priceCents: 4000,
    priceLabel: "AED 40 / 60",
    durationMinutes: 75,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 13,
    keyBenefits: ["Hands and feet", "Spa finish", "Classic care"],
  },
  {
    slug: "foot-spa",
    name: "Foot Spa",
    shortDescription: "Relaxing foot care and softening treatment.",
    fullDescription: "A calming foot spa that helps soften, refresh, and unwind tired feet.",
    priceCents: 3000,
    priceLabel: "AED 30",
    durationMinutes: 40,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 14,
    keyBenefits: ["Relaxation", "Softening", "Refresh"],
  },
  {
    slug: "mani-pedi-gelish-foot-spa",
    name: "Mani Gelish / Pedi Gelish w/ Foot Spa",
    shortDescription: "Long-lasting gel finish with spa pedicure care.",
    fullDescription: "Gelish manicure and pedicure services with a foot spa for polished, durable color and shine.",
    priceCents: 6000,
    priceLabel: "AED 60 / 80",
    durationMinutes: 90,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1610992015733-9e8f8aa6b9d6?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 15,
    keyBenefits: ["Gel shine", "Durability", "Pedicure spa"],
  },
  {
    slug: "soft-gel-extension",
    name: "Soft Gel Extension",
    shortDescription: "Lightweight extension with a natural feel.",
    fullDescription: "A soft gel extension service for flexible length and a refined natural-looking nail shape.",
    priceCents: 12000,
    priceLabel: "AED 120",
    durationMinutes: 90,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1596704017254-9b121068fb39?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 16,
    keyBenefits: ["Natural feel", "Flexible length", "Refined finish"],
  },
  {
    slug: "acrylic-extension",
    name: "Acrylic Extension",
    shortDescription: "Durable sculpted extension for stronger structure.",
    fullDescription: "A sculpted acrylic extension option that creates a stronger, longer-lasting nail structure.",
    priceCents: 20000,
    priceLabel: "AED 200",
    durationMinutes: 100,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 17,
    keyBenefits: ["Strong structure", "Sculpted shape", "Long wear"],
  },
  {
    slug: "hard-gel-biab-extension",
    name: "Hard Gel Extension / Biab",
    shortDescription: "Structured gel extension with flexible strength.",
    fullDescription: "A hard gel or BIAB-style extension service that adds structure while keeping the finish refined and wearable.",
    priceCents: 8000,
    priceLabel: "AED 80 / 100",
    durationMinutes: 100,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1610992035741-3c0a18f0a95b?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 18,
    keyBenefits: ["Structured support", "Flexible strength", "Refined finish"],
  },
  {
    slug: "refill-extension",
    name: "Refill Extension",
    shortDescription: "Refresh existing extensions and keep them seamless.",
    fullDescription: "A maintenance refill to keep extensions looking fresh, balanced, and well-blended between full sets.",
    priceCents: 8000,
    priceLabel: "AED 80 - 100",
    durationMinutes: 70,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1610992015593-9f3f1f393b21?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 19,
    keyBenefits: ["Maintenance", "Seamless look", "Extension care"],
  },
  {
    slug: "nail-removal",
    name: "Removal (Gelish / Hard / Acrylic)",
    shortDescription: "Safe removal service for all common nail systems.",
    fullDescription: "A careful removal treatment for gelish, hard gel, or acrylic nails to protect the natural nail underneath.",
    priceCents: 1000,
    priceLabel: "AED 10 / 30 / 80",
    durationMinutes: 45,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1609041336902-84f2f5d4c4c0?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 20,
    keyBenefits: ["Safe removal", "Natural nail care", "System specific"],
  },
  {
    slug: "nail-art",
    name: "Nail Art",
    shortDescription: "Custom nail design with simple to detailed finishes.",
    fullDescription: "Creative nail art from minimal details to more elaborate finishes depending on the look desired.",
    priceCents: 500,
    priceLabel: "AED 5 - 50",
    durationMinutes: 45,
    category: "Nail Care",
    imageUrl: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 21,
    keyBenefits: ["Custom design", "Creative finish", "Detail work"],
  },

  // Eyelash
  {
    slug: "classic-lashes",
    name: "Classic",
    shortDescription: "Natural lash enhancement with clean definition.",
    fullDescription: "A classic eyelash extension service that adds soft volume and definition without overpowering the eye.",
    priceCents: 12000,
    priceLabel: "AED 120",
    durationMinutes: 90,
    category: "Eyelash",
    imageUrl: "https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 22,
    keyBenefits: ["Natural definition", "Soft volume", "Clean finish"],
  },
  {
    slug: "volume-3d-5d",
    name: "Volume (3D / 5D)",
    shortDescription: "Layered volume for a fuller lash look.",
    fullDescription: "A fuller lash extension service built with 3D or 5D volume for a denser, more dramatic result.",
    priceCents: 18000,
    priceLabel: "AED 180 / 200",
    durationMinutes: 120,
    category: "Eyelash",
    imageUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 23,
    keyBenefits: ["Fuller look", "Layered volume", "Dramatic finish"],
  },
  {
    slug: "mega-volume",
    name: "Mega Volume",
    shortDescription: "Maximum fullness for a bold lash statement.",
    fullDescription: "An intense volume lash look for clients who want a more dramatic and high-impact finish.",
    priceCents: 25000,
    priceLabel: "AED 250",
    durationMinutes: 150,
    category: "Eyelash",
    imageUrl: "https://images.unsplash.com/photo-1517300181609-9f3f1f5f0b4e?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 24,
    keyBenefits: ["Maximum fullness", "Bold finish", "Statement look"],
  },
  {
    slug: "lash-lift",
    name: "Lash Lift",
    shortDescription: "Lift and curl natural lashes for open eyes.",
    fullDescription: "A natural lash enhancement that lifts and curls the lashes for a bright, wide-eyed finish.",
    priceCents: 7000,
    priceLabel: "AED 70",
    durationMinutes: 60,
    category: "Eyelash",
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 25,
    keyBenefits: ["Lifted curl", "Natural look", "Bright eyes"],
  },
  {
    slug: "brow-lamination",
    name: "Brow Lamination",
    shortDescription: "Smooth brow grooming for a fuller shape.",
    fullDescription: "A brow lamination service that smooths, shapes, and sets the brows for a more lifted appearance.",
    priceCents: 7000,
    priceLabel: "AED 70",
    durationMinutes: 60,
    category: "Eyelash",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27ec8229babb?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 26,
    keyBenefits: ["Brow shaping", "Lifted look", "Smooth finish"],
  },

  // Facial & Threading
  {
    slug: "facial-cleansing",
    name: "Facial Cleansing",
    shortDescription: "A clean reset for the skin with gentle cleansing care.",
    fullDescription: "A foundational facial cleansing ritual that refreshes the skin and prepares it for deeper treatment.",
    priceCents: 7000,
    priceLabel: "AED 70",
    durationMinutes: 45,
    category: "Facial & Threading",
    imageUrl: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 27,
    keyBenefits: ["Gentle cleanse", "Skin reset", "Fresh finish"],
  },
  {
    slug: "deep-cleansing-facial",
    name: "Deep Cleansing Facial",
    shortDescription: "Targeted cleansing to remove buildup and congestion.",
    fullDescription: "A deeper facial for skin that needs more thorough pore care, balance, and clarity.",
    priceCents: 9900,
    priceLabel: "AED 99",
    durationMinutes: 60,
    category: "Facial & Threading",
    imageUrl: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 28,
    keyBenefits: ["Deep cleanse", "Pore care", "Balanced skin"],
  },
  {
    slug: "brightening-gold-facial",
    name: "Brightening / Gold Facial",
    shortDescription: "Glow-focused facial with a luminous finish.",
    fullDescription: "A brightening facial that supports a more radiant complexion with a polished gold-toned finish.",
    priceCents: 9900,
    priceLabel: "AED 99",
    durationMinutes: 60,
    category: "Facial & Threading",
    imageUrl: "https://images.unsplash.com/photo-1566400205544-0c8d3b7a6c1a?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 29,
    keyBenefits: ["Glow support", "Radiance boost", "Luminous finish"],
  },
  {
    slug: "hydrafacial",
    name: "HydraFacial",
    shortDescription: "Hydration-led facial for a smooth, fresh complexion.",
    fullDescription: "A hydrating facial treatment that supports a cleaner, softer, and more refreshed skin surface.",
    priceCents: 12000,
    priceLabel: "AED 120",
    durationMinutes: 75,
    category: "Facial & Threading",
    imageUrl: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 30,
    keyBenefits: ["Hydration", "Smooth finish", "Fresh look"],
  },
  {
    slug: "dr-renaud",
    name: "Dr. Renaud",
    shortDescription: "Premium facial care for a more elevated skin ritual.",
    fullDescription: "An advanced facial service built around a more premium treatment experience and refined skin care.",
    priceCents: 22000,
    priceLabel: "AED 220",
    durationMinutes: 75,
    category: "Facial & Threading",
    imageUrl: "https://images.unsplash.com/photo-1570172619380-2126ad04840b?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 31,
    keyBenefits: ["Premium facial", "Elevated care", "Refined ritual"],
  },
  {
    slug: "upper-lip-eyebrow-threading",
    name: "Upper Lip / Eyebrow Threading",
    shortDescription: "Precise facial threading for clean definition.",
    fullDescription: "A precise threading service for upper lip and eyebrow shaping with a clean, polished result.",
    priceCents: 1000,
    priceLabel: "AED 10 / 20",
    durationMinutes: 30,
    category: "Facial & Threading",
    imageUrl: "https://images.unsplash.com/photo-1519415510236-8e1f3b0e3a7b?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 32,
    keyBenefits: ["Precise shaping", "Clean definition", "Quick care"],
  },
  {
    slug: "full-face-threading",
    name: "Full Face Threading",
    shortDescription: "Full-face threading for a smooth, defined result.",
    fullDescription: "A full-face threading service that removes unwanted hair and leaves the skin looking crisp and smooth.",
    priceCents: 4500,
    priceLabel: "AED 45",
    durationMinutes: 45,
    category: "Facial & Threading",
    imageUrl: "https://images.unsplash.com/photo-1500840216050-6ffa99d75160?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 33,
    keyBenefits: ["Smooth finish", "Facial definition", "Refined care"],
  },

  // Waxing
  {
    slug: "half-arm-full-arm-wax",
    name: "Half Arm / Full Arm",
    shortDescription: "Waxing for arm smoothness and clean skin.",
    fullDescription: "A waxing service for half-arm or full-arm removal, leaving the skin smooth and polished.",
    priceCents: 3000,
    priceLabel: "AED 30 / 50",
    durationMinutes: 30,
    category: "Waxing",
    imageUrl: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 34,
    keyBenefits: ["Smooth skin", "Arm care", "Clean finish"],
  },
  {
    slug: "half-leg-full-leg-wax",
    name: "Half Leg / Full Leg",
    shortDescription: "Leg waxing with smooth, clean results.",
    fullDescription: "A waxing service for half-leg or full-leg hair removal with a neat, polished finish.",
    priceCents: 4000,
    priceLabel: "AED 40 / 60",
    durationMinutes: 40,
    category: "Waxing",
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 35,
    keyBenefits: ["Smooth legs", "Clean finish", "Wax care"],
  },
  {
    slug: "underarm-wax",
    name: "Underarm",
    shortDescription: "Quick underarm waxing for freshness and ease.",
    fullDescription: "A focused underarm waxing service that keeps the area smooth and clean.",
    priceCents: 1500,
    priceLabel: "AED 15",
    durationMinutes: 20,
    category: "Waxing",
    imageUrl: "https://images.unsplash.com/photo-1595475038678-7c01c46b0c9e?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 36,
    keyBenefits: ["Quick care", "Fresh feel", "Clean skin"],
  },
  {
    slug: "full-body-wax",
    name: "Full Body",
    shortDescription: "Complete waxing service for a polished all-over finish.",
    fullDescription: "A full-body waxing service for a cleaner, smoother feel across multiple areas.",
    priceCents: 15000,
    priceLabel: "AED 150",
    durationMinutes: 90,
    category: "Waxing",
    imageUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 37,
    keyBenefits: ["All-over smoothness", "Full-body care", "Clean finish"],
  },
  {
    slug: "brazilian-wax",
    name: "Brazilian",
    shortDescription: "Detailed waxing service with a neat finish.",
    fullDescription: "A Brazilian waxing service performed with care for a smooth, clean result.",
    priceCents: 6000,
    priceLabel: "AED 60",
    durationMinutes: 45,
    category: "Waxing",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6a5a1a?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 38,
    keyBenefits: ["Detailed care", "Smooth finish", "Professional waxing"],
  },
  {
    slug: "upper-lip-eyebrow-wax",
    name: "Upper Lip / Eyebrow",
    shortDescription: "Simple facial waxing for quick grooming.",
    fullDescription: "A gentle waxing service for the upper lip or eyebrow area to keep the features neat and defined.",
    priceCents: 1000,
    priceLabel: "AED 10",
    durationMinutes: 20,
    category: "Waxing",
    imageUrl: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 39,
    keyBenefits: ["Quick grooming", "Definition", "Gentle care"],
  },

  // Relaxing Massage
  {
    slug: "full-body-massage",
    name: "Full Body (1 Hour)",
    shortDescription: "A restorative full-body massage experience.",
    fullDescription: "A one-hour massage designed to ease tension, restore calm, and reset the body.",
    priceCents: 12000,
    priceLabel: "AED 120",
    durationMinutes: 60,
    category: "Relaxing Massage",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6a5a1a?w=1200&auto=format&fit=crop",
    featured: true,
    active: true,
    sortOrder: 40,
    keyBenefits: ["Deep relaxation", "Restored calm", "Full body care"],
  },
  {
    slug: "massage-short",
    name: "Massage (15 min / 30 min)",
    shortDescription: "A shorter massage option for targeted relief.",
    fullDescription: "A quick massage service that focuses on releasing tension and relaxing specific areas.",
    priceCents: 3000,
    priceLabel: "AED 30 / 60",
    durationMinutes: 30,
    category: "Relaxing Massage",
    imageUrl: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 41,
    keyBenefits: ["Targeted relief", "Calming care", "Time friendly"],
  },
  {
    slug: "head-shoulder-massage",
    name: "Head & Shoulder (30 min)",
    shortDescription: "Focused massage for upper-body tension.",
    fullDescription: "A 30-minute massage aimed at easing the head, neck, and shoulder area.",
    priceCents: 6000,
    priceLabel: "AED 60",
    durationMinutes: 30,
    category: "Relaxing Massage",
    imageUrl: "https://images.unsplash.com/photo-1571019613914-85f342c1d34c?w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 42,
    keyBenefits: ["Upper-body relief", "Calming touch", "Stress release"],
  },
];

// These are the staff cards shown on the artisans page and in admin tools.
// The same records also feed the stylist dropdowns used by booking and moderation screens.
export const defaultStylists = [
  // Elena is the main featured specialist in the public team showcase.
  {
    name: "Elena Vance",
    role: "Master Aesthetician",
    bio:
      "With over 15 years in luxury skincare, Elena specializes in dermal sculpting and bespoke botanical infusions. Her philosophy centers on cellular regeneration and long-term vitality.",
    imageUrl: "https://images.unsplash.com/photo-1594744803329-a584af1cae02?q=80&w=800&auto=format&fit=crop",
    specialties: ["Dermal sculpting", "Botanical infusion", "Skin renewal"],
    featured: true,
    active: true,
    sortOrder: 1,
  },
  // Julian is the consulting-focused specialist with a calmer, more analytical profile.
  {
    name: "Julian Thorne",
    role: "Skin Health Consultant",
    bio:
      "Julian approaches beauty through the lens of chemistry and wellness. His curative sessions focus on inflammatory balance and protective barriers for sensitive complexions.",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=800&auto=format&fit=crop",
    specialties: ["Barrier care", "Consultation", "Inflammation balance"],
    featured: false,
    active: true,
    sortOrder: 2,
  },
  // Sienna rounds out the team with a more experience-led ritual design role.
  {
    name: "Sienna Rose",
    role: "Ritual Architect",
    bio:
      "The creator of our signature Luminous Flow, Sienna bridges the gap between holistic meditation and advanced facials to create a transcendental beauty experience.",
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800&auto=format&fit=crop",
    specialties: ["Holistic rituals", "Facial design", "Luxury experience"],
    featured: true,
    active: true,
    sortOrder: 3,
  },
];

// These promotions power the offers page and the seasonal specials section.
// Each one is shaped to be a small marketing card rather than a full landing page.
export const defaultPromotions = [
  // This is the main membership offer that the offers page highlights first.
  {
    title: "Glow Membership",
    description:
      "Join our monthly membership for continuous care, bespoke treatments, and exclusive member-only perks designed for year-round radiance.",
    code: "GLOW20",
    imageUrl: "https://i.pinimg.com/originals/6e/48/e1/6e48e1bfeebc6ddd41b2e45286fa60fc.jpg",
    tag: "Most Popular",
    discountText: "20% off select services",
    featured: true,
    active: true,
    sortOrder: 1,
    startDate: "2024-01-01",
    endDate: "2026-12-31",
  },
  // This one changes with the season so the site can feel current.
  {
    title: "Seasonal Rituals",
    description:
      "Experience transformative treatments carefully customized for the current season's unique environmental challenges and skin needs.",
    code: "SEASONAL",
    imageUrl: "https://i.pinimg.com/736x/3f/83/d4/3f83d4777ddd2ebd201ce376c53af924.jpg",
    tag: "Limited Time",
    discountText: "Seasonal curation savings",
    featured: true,
    active: true,
    sortOrder: 2,
    startDate: "2024-01-01",
    endDate: "2026-12-31",
  },
  // This card is the value-focused bundle offer.
  {
    title: "Bundle & Save",
    description:
      "Combine multiple signature services and take home our premium retail products for exceptional exclusive savings.",
    code: "BUNDLE15",
    imageUrl: "https://i.pinimg.com/1200x/66/7f/71/667f717825dc54f377aa4612c9439609.jpg",
    tag: "Best Value",
    discountText: "Bundle package savings",
    featured: true,
    active: true,
    sortOrder: 3,
    startDate: "2024-01-01",
    endDate: "2026-12-31",
  },
];

// These gallery items are the visual catalogue for the lounge.
// The gallery page and homepage pull from the same set so the visuals stay in sync.
export const defaultGalleryItems = [
  // This is the hero product edit that opens the gallery set.
  {
    title: "Radiance Elixir",
    category: "Product Edit",
    caption: "A luminous bottled ritual.",
    altText: "Luxury serum bottle",
    imageUrl: "https://i.pinimg.com/1200x/a3/43/df/a343dfb6e615e0e65a48411ab0ab833a.jpg",
    featured: true,
    active: true,
    sortOrder: 1,
  },
  // Texture-focused image that gives the gallery some softness.
  {
    title: "Satin Touch",
    category: "Texture Study",
    caption: "Cream textures in motion.",
    altText: "Cream texture study",
    imageUrl: "https://i.pinimg.com/1200x/66/23/9a/66239a1485de08d7c9d73f52e4ca2408.jpg",
    featured: true,
    active: true,
    sortOrder: 2,
  },
  // A wide interior image that helps show the lounge atmosphere.
  {
    title: "The Sanctuary",
    category: "Space",
    caption: "A calm interior with editorial light.",
    altText: "Spa interior",
    imageUrl: "https://i.pinimg.com/736x/b8/ec/cb/b8eccbefb90d0b642f1152624fa09459.jpg",
    featured: true,
    active: true,
    sortOrder: 3,
  },
  // Warm amber tones are used here to add contrast.
  {
    title: "Golden Hour",
    category: "Oil Infusion",
    caption: "Amber glass and tonal warmth.",
    altText: "Face oil bottle",
    imageUrl: "https://i.pinimg.com/1200x/a3/20/48/a320481f501bec266ffc9c8c494cff69.jpg",
    featured: false,
    active: true,
    sortOrder: 4,
  },
  // Dark velvet keeps the visual mood a little more dramatic.
  {
    title: "Velvet Lounge",
    category: "Interior",
    caption: "Dark velvet and layered shadows.",
    altText: "Spa lounge interior",
    imageUrl: "https://i.pinimg.com/736x/26/8d/22/268d22a96e65f8e21b6ea4836e1a3644.jpg",
    featured: false,
    active: true,
    sortOrder: 5,
  },
  // This shot shows a hands-on self-care ritual.
  {
    title: "The Ritual",
    category: "Self Care",
    caption: "A moment of hands-on restoration.",
    altText: "Woman applying cream",
    imageUrl: "https://i.pinimg.com/1200x/67/fb/63/67fb63d99a2ea5fce9cb0a074d6b73ba.jpg",
    featured: true,
    active: true,
    sortOrder: 6,
  },
  // Bottles and tools give the catalogue a more curated shelf look.
  {
    title: "Curated Essentials",
    category: "Collection",
    caption: "A library of bottles and tools.",
    altText: "Collection of bottles",
    imageUrl: "https://i.pinimg.com/736x/5c/16/eb/5c16eb439f95a147912e87c8f4a297d1.jpg",
    featured: false,
    active: true,
    sortOrder: 7,
  },
  // Abstract light is used to break up the product imagery.
  {
    title: "Inner Glow",
    category: "Abstract",
    caption: "A luminous abstract moment.",
    altText: "Abstract light glow",
    imageUrl: "https://i.pinimg.com/736x/74/3e/7e/743e7e91713fd66db2f223afe5c2255e.jpg",
    featured: false,
    active: true,
    sortOrder: 8,
  },
  // This microscopic edit keeps the gallery feeling precise and editorial.
  {
    title: "Botanical Essence",
    category: "Micro Edit",
    caption: "A precise dropper composition.",
    altText: "Botanical essence dropper",
    imageUrl: "https://images.unsplash.com/photo-1616394584738-fc6e612ca8d8?q=80&w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 9,
  },
  // Minimalist shelf styling keeps the feed from feeling too busy.
  {
    title: "The Shelfie",
    category: "Minimalism",
    caption: "Minimal bath styling and calm surfaces.",
    altText: "Minimalist skincare shelf",
    imageUrl: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 10,
  },
  // This close-up skin image reinforces the skincare focus.
  {
    title: "Raw Texture",
    category: "Skin Study",
    caption: "Close-up skin detail and tone.",
    altText: "Raw skin texture",
    imageUrl: "https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 11,
  },
  // The tool shot closes the gallery with a more technical finish.
  {
    title: "Crafted Precision",
    category: "Tools",
    caption: "Luxury instruments in focus.",
    altText: "Luxury spa tools",
    imageUrl: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?q=80&w=1200&auto=format&fit=crop",
    featured: false,
    active: true,
    sortOrder: 12,
  },
];

// These reviews are starter testimonials so the homepage does not look empty.
// They are approved up front because they are meant to be visible on first launch.
export const defaultReviews = [
  // This review is the long, detailed guest story that opens the set.
  {
    name: "Gerardine Alcala",
    role: "Verified Guest",
    email: "gerardine@example.com",
    avatarUrl: "",
    rating: 5,
    mainQuote:
      "It was my first time visiting, and I had a wonderful experience. The salon is clean, and the staff are warm, welcoming, and very accommodating. It truly feels like a hidden gem in the area.",
    subQuote1:
      "I availed their points package, which is a great deal considering the quality of care and service they provide. I had a haircut, brow threading, waxing, and a mani-pedi. Ate Marilyn did such a lovely job with my haircut, and Ms. Hanan cleaned up my brows so well.",
    subQuote2:
      "The waxing was done smoothly with minimal discomfort, and Ate Mavi and Lean made sure I was comfortable throughout the process. I’ll definitely be coming back and would highly recommend this place!",
    serviceName: "Pedicure, Waxing, Manicure",
    featured: true,
    isApproved: true,
    sortOrder: 1,
  },
  // The second review is a shorter but equally positive guest note.
  {
    name: "Mikaelah Paloma",
    role: "Verified Guest",
    email: "mikaelah@example.com",
    avatarUrl: "",
    rating: 5,
    mainQuote:
      "First time getting my hair done in Dubai and I didn’t regret trying Sibs Style Beauty Lounge at all.",
    subQuote1:
      "The staff were very accommodating, and the place is spacious, clean, and overall very pleasant. Special thanks to my hairdresser and lash tech 🥰",
    subQuote2:
      "I’ll definitely come back 🤍 Highly recommended for anyone looking for quality service in a beautiful environment!",
    serviceName: "Hairstyling, Eyelash extensions",
    featured: true,
    isApproved: true,
    sortOrder: 2,
  },
  // This last one keeps the page feeling balanced with another verified voice.
  {
    name: "Guendez Narimane",
    role: "Verified Guest",
    email: "guendez@example.com",
    avatarUrl: "",
    rating: 5,
    mainQuote:
      "Atmosphere service and prices are excellent, it's a pleasure experiencing this especially in this area.",
    subQuote1:
      "I did waxing with miss fulla the owner of the saloon. It's honestly a very very good experience i will definitely come back again!",
    subQuote2:
      "The professionalism and welcoming nature of the entire team made it a standout visit. Five stars!",
    serviceName: "Waxing, Manicure",
    featured: true,
    isApproved: true,
    sortOrder: 3,
  },
];

export const defaultAdminCredentials = {
  // The real values should come from env vars on your machine, not from GitHub.
  // These defaults exist only so a fresh local database can be seeded without extra setup.
  fullName: process.env.DEFAULT_ADMIN_FULLNAME || "Sibs Style Admin",
  // The admin email is normalized later so sign-in uses one predictable address.
  email: process.env.DEFAULT_ADMIN_EMAIL || "admin@example.com",
  // This phone number is only a placeholder until you supply your own environment value.
  phone: process.env.DEFAULT_ADMIN_PHONE || "000-000-0000",
  // NOTE: For security, set a strong password in your local env (DEFAULT_ADMIN_PASSWORD).
  // The fallback below is intentionally weak so the seeded account is not privileged in public repos.
  // The weak fallback is deliberate because this file is part of a public seed set.
  password: process.env.DEFAULT_ADMIN_PASSWORD || "changeme",
};
